### ISSUE TITLE
Custom Commands

### ISSUE THREAD

**Issue by kman1898** [bitfocus/companion-module-novastar-h-series#6]
Hello, I have the signed NDA from novastar, can someone help me with how to implement  custom commands for h series?

e.g. Fade to Black or Take?

**Comment by rit3sh7** [comment]
Did they send you the H series protocols document?

**Comment by kman1898** [comment]
Yes, I’ve got it for a few different nova products h series included. 

but I don’t want to send the incorrect command and the commands are a bit daunting to the uninitiated

**Comment by kman1898** [comment]
Never mind. Apparently I was looking at the wrong command document. The h series one is very detailed in how these commands are made.
